name: Checkov Terraform Security Scan

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.tf'
      - 'terraform.tfvars'
      - '.github/workflows/chekov-scan.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**.tf'
      - 'terraform.tfvars'

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          quiet: false
          soft_fail: false
          skip_check: CKV_AWS_1,CKV_AWS_18
          output_format: sarif
          output_file_path: reports/checkov.sarif

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/checkov.sarif
          category: checkov

      - name: Comment PR with Checkov results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const sarifData = JSON.parse(fs.readFileSync('reports/checkov.sarif', 'utf8'));
            
            let comment = '## ðŸ”’ Checkov Security Scan Results\n\n';
            
            if (sarifData.runs[0].results.length === 0) {
              comment += 'âœ… No security issues found!\n';
            } else {
              comment += `âš ï¸ Found ${sarifData.runs[0].results.length} security issue(s):\n\n`;
              
              sarifData.runs[0].results.forEach(result => {
                comment += `- **${result.ruleId}**: ${result.message.text}\n`;
                comment += `  Location: ${result.locations[0].physicalLocation.artifactLocation.uri}\n\n`;
              });
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
